#!/bin/sh
set -e
if [ ! -d artifacts ]; then
  mkdir artifacts
fi
cd artifacts
if [ ! -d Release ]; then
  mkdir Release
fi
cd Release
# Default to clang, but use CXX if it is set already.
if [ -z "$CXX" ]; then
  export CXX=clang++
fi
cmake -DCMAKE_BUILD_TYPE=Release ../.. -GNinja
ninja
./test/tests
cd ../..
