#!/bin/sh
set -e
if [ ! -d artifacts ]; then
  mkdir artifacts
fi
cd artifacts
if [ ! -d Ubsan ]; then
  mkdir Ubsan
fi
cd Ubsan
if [ -n "$COMPILER" ]; then
  echo "COMPILER is defined, use it: CXX=$COMPILER"
  export CXX=$COMPILER
fi
if [ -z "$CXX" ]; then
  export CXX=clang++
fi
cmake -DSANITIZE_UNDEFINED=On ../.. -GNinja
ninja
./test/tests
cd ../..
