#!/bin/sh
set -e
if [ ! -d artifacts ]; then
  mkdir artifacts
fi
cd artifacts
if [ ! -d Asan ]; then
  mkdir Asan
fi
cd Asan
if [ -n "$COMPILER" ]; then
  echo "COMPILER is defined, use it: CXX=$COMPILER"
  export CXX=$COMPILER
fi
if [ -z "$CXX" ]; then
  export CXX=clang++
fi
cmake -DSANITIZE_ADDRESS=On ../.. -GNinja
ninja
./test/tests
cd ../..
