#!/bin/sh
set -e
if [ ! -d artifacts ]; then
  mkdir artifacts
fi
cd artifacts
if [ ! -d Debug ]; then
  mkdir Debug
fi
cd Debug
if [ -n "$COMPILER" ]; then
  echo "COMPILER is defined, use it: CXX=$COMPILER"
  export CXX=$COMPILER
fi
if [ -z "$CXX" ]; then
  export CXX=clang++
fi
cmake -DCMAKE_BUILD_TYPE=Debug ../.. -GNinja
ninja
./test/tests
cd ../..
ln -sf artifacts/Debug/compile_commands.json compile_commands.json
